"""FAISS vector store: build from the knowledge base, then load for querying.

Design notes (be ready to explain these in the viva):

* **What is stored** - chunks of the curated career knowledge base in
  `backend/rag/knowledge_base/`, plus the metadata we attach at ingest time
  (source filename, human-readable title, topic).
* **How chunking works** - `RecursiveCharacterTextSplitter` with a 900-character
  window and 150-character overlap. It splits on paragraph breaks first, then
  lines, then sentences, so a chunk rarely cuts a sentence in half. The overlap
  means a fact sitting on a chunk boundary still appears whole in one chunk.
* **How embeddings are generated** - Google `text-embedding-004` turns each chunk
  into a 768-dimension vector. The identical model is used for the query.
* **How retrieval works** - the query is embedded, FAISS runs an inner-product /
  L2 nearest-neighbour search over the chunk vectors, and the top-k chunks come
  back with a similarity score.
"""

from __future__ import annotations

import logging
from pathlib import Path

from langchain_community.vectorstores import FAISS
from langchain_core.documents import Document
from langchain_text_splitters import RecursiveCharacterTextSplitter

from backend.config import get_settings
from backend.core.llm import get_embeddings

logger = logging.getLogger(__name__)

_cached_store: FAISS | None = None


def load_knowledge_base_documents() -> list[Document]:
    """Read every markdown file in the knowledge base into a Document."""
    settings = get_settings()
    kb_dir: Path = settings.knowledge_base_dir

    if not kb_dir.exists():
        raise FileNotFoundError(f"Knowledge base directory not found: {kb_dir}")

    documents: list[Document] = []
    for path in sorted(kb_dir.glob("*.md")):
        text = path.read_text(encoding="utf-8").strip()
        if not text:
            logger.warning("Skipping empty knowledge base file: %s", path.name)
            continue

        # First markdown heading becomes the document title, used in citations.
        title = path.stem.replace("_", " ").title()
        for line in text.splitlines():
            if line.startswith("# "):
                title = line.lstrip("# ").strip()
                break

        documents.append(
            Document(
                page_content=text,
                metadata={
                    "source": path.name,
                    "title": title,
                    "topic": path.stem,
                },
            )
        )

    logger.info("Loaded %d knowledge base documents from %s", len(documents), kb_dir)
    return documents


def split_documents(documents: list[Document]) -> list[Document]:
    """Chunk documents so each retrieved passage fits comfortably in a prompt."""
    settings = get_settings()
    splitter = RecursiveCharacterTextSplitter(
        chunk_size=settings.chunk_size,
        chunk_overlap=settings.chunk_overlap,
        separators=["\n\n", "\n", ". ", " ", ""],
        length_function=len,
    )
    chunks = splitter.split_documents(documents)

    # Give every chunk a stable id, which makes traces easier to read.
    for index, chunk in enumerate(chunks):
        chunk.metadata["chunk_id"] = f"{chunk.metadata.get('topic', 'doc')}-{index}"

    logger.info("Split %d documents into %d chunks", len(documents), len(chunks))
    return chunks


def build_vector_store(force: bool = False) -> FAISS:
    """Embed the knowledge base and persist a FAISS index to disk."""
    settings = get_settings()
    index_dir = settings.vector_store_dir

    if index_dir.exists() and not force:
        logger.info("Index already exists at %s (use force=True to rebuild).", index_dir)
        return load_vector_store()

    chunks = split_documents(load_knowledge_base_documents())
    if not chunks:
        raise ValueError("No chunks produced. Is the knowledge base empty?")

    logger.info("Embedding %d chunks with %s ...", len(chunks), settings.embedding_model)
    store = FAISS.from_documents(chunks, get_embeddings())

    index_dir.mkdir(parents=True, exist_ok=True)
    store.save_local(str(index_dir))
    logger.info("Saved FAISS index to %s", index_dir)

    global _cached_store
    _cached_store = store
    return store


def load_vector_store() -> FAISS:
    """Load the persisted index, building it on first run if absent."""
    global _cached_store
    if _cached_store is not None:
        return _cached_store

    settings = get_settings()
    index_dir = settings.vector_store_dir

    if not (index_dir / "index.faiss").exists():
        logger.warning("No index found at %s. Building it now.", index_dir)
        return build_vector_store(force=True)

    # The index is generated by this project, so deserialization is safe here.
    _cached_store = FAISS.load_local(
        str(index_dir),
        get_embeddings(),
        allow_dangerous_deserialization=True,
    )
    logger.info("Loaded FAISS index from %s", index_dir)
    return _cached_store


def get_retriever(top_k: int | None = None):
    """Return a LangChain retriever over the knowledge base."""
    settings = get_settings()
    return load_vector_store().as_retriever(
        search_kwargs={"k": top_k or settings.retriever_top_k}
    )
